name: car_driver_alert_system
description: "A Flutter app that monitors driver drowsiness using face detection and provides real-time alerts to prevent accidents."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # Firebase (for authentication and data storage)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  flutter_secure_storage: ^9.2.4
  
  # Google ML Kit (Vision APIs for face detection)
  google_ml_kit: ^0.20.0
  google_mlkit_commons: ^0.11.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_face_mesh_detection: ^0.4.1
  
  # TensorFlow Lite for custom model inference
  tflite_flutter: ^0.11.0
  
  # Charts for data visualization
  syncfusion_flutter_charts: ^30.2.5

  # Camera and permissions
  camera: ^0.11.2
  permission_handler: ^12.0.1
  
  # Audio and Bluetooth for alerts
  audioplayers: ^6.5.0
  flutter_blue_plus: ^1.34.4
  wakelock_plus: ^1.0.0
  
  # Overlay Window for PIP-like functionality
  system_alert_window: ^2.0.7
  
  # Shared preferences for data persistence
  shared_preferences: ^2.3.0
  
  # Additional utilities
  provider: ^6.1.0
  
  # JavaScript interoperability for web
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
  
  # Add fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
